### ISSUE TITLE
Unclear README (user error?)

### ISSUE THREAD

**Issue by 1ynn1ei** [Ajatt-Tools/anki.koplugin#30]
* KOReader version:
2024.07

**Describe the Issue**
I have my laptop running anki with AnkiConnect. I have adjusted it as per the README. I have installed the latest (master) plugin on my ereader, and have verified it is in the plugin list. I have Anki settings. When I select a word, it does not give me the "Add to Anki" button. I have tested this with vocab builder both disabled and enabled.

**How to Reproduce (if relevant)**
Install anki.koplugin on KOReader 2024.07 . Change no other settings.

**crash.log**
[crash.log](https://github.com/user-attachments/files/16246281/crash.log)
a quick grep shows no anki mention in the crash.log

**Additional context**
Using a BOOX Page if that matters.

**Comment by nairyosangha** [comment]
No user error here it looks like, I see some messages related to the plugin in that log (try case insensitive grep :)

Assuming those weird segfaults play no part here, this is probably because of this: https://github.com/Ajatt-Tools/anki.koplugin/issues/22

Since 2024.07 is the first new release this broke, so hopefully it should work again after the latest commit

**Comment by 1ynn1ei** [comment]
wow total drop on my part for the insensitive grep thing. apologies for that! I tested with the latest push and it works. I really appreciate the quick turnaround on that.
