### ISSUE TITLE
Feature Request: Reading Field

### ISSUE THREAD

**Issue by konomu** [Ajatt-Tools/anki.koplugin#33]
I feel like this addon would really benefit from support for the reading field. Almost all Mining notetypes I've seen have one, so why isn't it already implemented here? The reading already shows up in the first line of the dictionary entry, but since I already have a separate field for the reading, it clashes with the style of the rest of my mining cards from other sources.

**Comment by konomu** [comment]
I just realized the pitch accent extension pretty much does this. Never mind lol

**Comment by nairyosangha** [comment]
Ya the code that extract this stuff is already there because I needed it for that multi_def and pitch-accent extensions.
I posted an example here: https://github.com/Ajatt-Tools/anki.koplugin/issues/26#issuecomment-2143385710

I didn't add it to the actual extensions because it doesn't really seem worth it to me, since there's external tools that can do that, I mentioned that in the other issue as well
