### ISSUE TITLE
Is there a way to populate 2 fields with the vocab word?

### ISSUE THREAD

**Issue by YashaNoos** [Ajatt-Tools/anki.koplugin#43]
Hi long time no see! :p 

I use "JP mining note" and need to populate 2 fields with the vocab word namely "key"and "word".
I was wondering if it was possible to set it up in the profile lua.
I tried things like =>
`word_field = "key", "word",`
Without success so far.

Have a nice day and a merry Christmas if you are celebrating!

**Comment by nairyosangha** [comment]
Hello again, merry Christmas to you too :christmas_tree: 

What you're trying to do is not possible, not like that at least. The configuration file expects a field to have a single string as value, what you tried there is not even valid lua syntax so that wouldn't work.

You could however easily get what you want by making your own extension, something like
```lua
local conf = require("configuration")
local JP_mining_note = {}

function JP_mining_note:run(note)
    local vocab_word = note.fields[conf.word_field:get_value()]
    note.fields["word"] = vocab_word
    note.fields["key"] = vocab_word
    return note
end
return JP_mining_note
```
saved in the extensions folder with a filename like `EXT_JP_mining_note.lua` should do the trick

**Comment by YashaNoos** [comment]
Thanks for the quick response!
I created the `EXT_JP_mining_note.lua` with the code inside and put it in the extension folder
Enabled it in my profile `Japanese.lua`
```
    enabled_extensions = {
        --[[
        "EXT_dict_edit.lua",
        "EXT_dict_word_lookup.lua",
        "EXT_multi_def.lua",
        "EXT_pitch_accent.lua"
        "EXT_JP_mining_note.lua"
        --]]
```
But only the key field gets populated with the vocab word, maybe I should put something special in the word_field?
Currently I have :
`word_field = "key", `
If I replace key by anything else I get the "cannot create note because it is empty" error.

**Comment by nairyosangha** [comment]
Going by the snippet you posted, it's not working because the `enabled_extensions` table is empty as far as lua knows.
A comment in lua starts with `--`, a multiline comment starts with `[[` and is closed with `]]`, by putting `--` in front of it you can 'break' the multiline comment by just adding an extra `-`, you can tell below by the syntax highlighting.
```lua
    enabled_extensions = {
        --[[
        "EXT_dict_edit.lua",
        "EXT_dict_word_lookup.lua",
        "EXT_multi_def.lua",
        "EXT_pitch_accent.lua"
        "EXT_JP_mining_note.lua"
        --]]
```
```lua
    enabled_extensions = {
        ---[[
        "EXT_dict_edit.lua",
        "EXT_dict_word_lookup.lua",
        "EXT_multi_def.lua",
        "EXT_pitch_accent.lua"
        "EXT_JP_mining_note.lua"
        --]]
```

**Comment by YashaNoos** [comment]
Nairyosangha you did it again! I just had to add a coma that I forgot after "EXT_pitch_accent.lua" and It works perfectly, I can now mine on my kobo using my weird note type. Thanks a lot for your time and dedication to this project!
